### ISSUE TITLE
Related patterns

### ISSUE THREAD

**Issue by bumbleblue** [simplysecure/dots-website#67]
What's the best way to link to related patterns?

I've started using the category "related" in the YAML, e.g. here https://github.com/simplysecure/dots-patterns/blob/master/patterns/discovery-pub.md

Is there a better way?

**Comment by bumbleblue** [comment]
Also: shall I add `description` is the YAML also? This is the text that gets displayed in the Pattern Index page, so should probably be <140 characters?

**Comment by bumbleblue** [comment]
And shamelessly adding `category` for the top-level distinction. Glad all changes can be undone!

**Comment by okdistribute** [comment]
Awesome @bumbleblue! Yeah I like the idea of adding a description & using a `related` YAML tag.

I'm also fine with using `category` -- we just have to make sure that the corresponding category with the same name exists in the [`topics`](https://github.com/simplysecure/dots-patterns/tree/master/topics) directory.

**Comment by cafca** [comment]
I had imagined `related` to be "any pattern that gets linked to from within the text". If we have distinct `related` metadata we might also want to qualify *how* they are related. It's not immediately obvious to me why *content curators* is related to *discovery pub*. Those could be something like "goes along well with..." or "requires...".

**Comment by cafca** [comment]
The metadata format and requirements will solidify more as I implement bits and pieces of the full site, right now I can't tell you exactly what would be the best way to express things like *related patterns*. I will create documentation about the purpose of each field eventually.

**Comment by okdistribute** [comment]
@cafca Ah yes, that would be cool. I'd prefer to have "any pattern that gets linked to from within the text" to count as `related`... that would make it easier to keep it up to date, I think, rather than having to maintain all the markdown files with related patterns

**Comment by cafca** [comment]
@bumbleblue you can go ahead and close this if that answers your question for now :)
